### ISSUE TITLE
.env.test file ignored when running tests with @percy/agent

### ISSUE THREAD

**Issue by grzuy** [percy/percy-js#199]
Hi,

Given a Rails app with `dotenv-rails` and a `.env.test` file.
When running rails app tests preceded with `yarn percy exec`.
`.env.test` is ignored.

I built a test app reproducing this, with test green on `master`, and showing the issue on a sample PR that adds percy-capybara and @percy/agent (as recommended in the doc): https://github.com/grzuy/visual_tested_app/pull/1.

Thank you!

**Comment by grzuy** [comment]
Makes sense!

Thank you again!

**Comment by grzuy** [comment]
> I'm going to move this issue over to the `percy-client` repo and open up a PR shortly there to add support for environment based `.env` files

@wwilsman In case that trying to adapt other languages dotenv behaviour is too much, having the possibility of optionally disabling dotenv-js for percy-js would suffice in our case.

I mean

```
DISABLE_DOTENV_JS=1 yarn percy exec bin/rails test
```

Right?

**Comment by wwilsman** [comment]
Just created the PR! Once it's merged, the `NODE_ENV` environment variable must be set for environment specific dotenv files. So to load your production dotenv files, you'll want to set `NODE_ENV=production`. I also made sure to mimic dotenv-rails exclusion of `.env.local` when `NODE_ENV=test`.

**Comment by wwilsman** [comment]
Just released 3.8.0 which should have the new behavior! You can also now disable Percy's dotenv loading by setting `PERCY_DISABLE_DOTENV=1` (or to any value really).

Since this package is a transitive dependency, if you have trouble updating you'll have to uninstall and reinstall your SDK. You can also make sure you have the newest version by running `npm ls percy-client`.

Let me know if it works! 😃

**Comment by grzuy** [comment]
Both `NODE_ENV=test` and `PERCY_DISABLE_DOTENV=1` fixes our use case.

Thank you for the quick turnaround.
